import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

export default StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
  },
  container: {
    padding: Theme.spacing.lg,
    backgroundColor: Theme.colors.background,
  },
  header: {
    fontSize: Theme.typography.fontSizes.xxxl,
    fontWeight: Theme.typography.fontWeights.bold,
    marginBottom: Theme.spacing.lg,
    color: Theme.colors.dark,
  },
  card: {
    backgroundColor: Theme.colors.white,
    borderRadius: Theme.borderRadius.lg,
    padding: Theme.spacing.md + 2,
    marginBottom: Theme.spacing.md,
    ...Theme.shadows.md,
    borderWidth: 1,
    borderColor: Theme.colors.light,
    minHeight: 170,
    justifyContent: 'space-between',
  },
  cardLabel: {
    fontSize: Theme.typography.fontSizes.xs,
    fontWeight: Theme.typography.fontWeights.bold,
    color: Theme.colors.dark,
    marginBottom: 2,
    flexShrink: 1,
    flexWrap: 'wrap',
    lineHeight: 14,
    maxWidth: '100%',
  },
  cardDescription: {
    fontSize: Theme.typography.fontSizes.xs + 1,
    color: Theme.colors.medium,
    lineHeight: 17,
    flexShrink: 1,
    flexWrap: 'wrap',
    marginBottom: Theme.spacing.sm,
    maxWidth: '100%',
  },
  cardAmount: {
    fontSize: Theme.typography.fontSizes.xxl - 2,
    fontWeight: Theme.typography.fontWeights.bold,
    marginTop: Theme.spacing.sm + 2,
    flexShrink: 1,
    flexWrap: 'wrap',
    marginBottom: Theme.spacing.sm + 2,
    maxWidth: '100%',
  },
  cardTitleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: Theme.spacing.sm + 4,
  },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.borderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.sm + 4,
  },
  negative: {
    color: Theme.colors.error,
  },
  navSection: {
    marginTop: Theme.spacing.lg,
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm + 4,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.light,
  },
  navLabel: {
    fontSize: Theme.typography.fontSizes.md,
    marginLeft: Theme.spacing.sm + 4,
    color: Theme.colors.info,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  yearSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.sm + 4,
    marginBottom: Theme.spacing.sm,
  },
  yearSelectorLabel: {
    color: Theme.colors.medium,
    fontSize: Theme.typography.fontSizes.md - 1,
    marginRight: Theme.spacing.sm,
  },
  yearSelectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.primaryLight,
    borderRadius: Theme.borderRadius.sm,
    paddingHorizontal: Theme.spacing.sm + 4,
    paddingVertical: Theme.spacing.xs,
  },
  yearSelectorText: {
    color: Theme.colors.primary,
    fontWeight: Theme.typography.fontWeights.semiBold,
    fontSize: Theme.typography.fontSizes.md,
    marginRight: Theme.spacing.xs,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearPickerContainer: {
    backgroundColor: Theme.colors.white,
    borderRadius: Theme.borderRadius.md,
    padding: Theme.spacing.md,
    width: '80%',
    maxWidth: 300,
  },
  yearOption: {
    paddingVertical: Theme.spacing.sm + 4,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.borderRadius.sm,
    marginBottom: Theme.spacing.sm,
  },
  selectedYearOption: {
    backgroundColor: Theme.colors.primary,
  },
  yearOptionText: {
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.dark,
    textAlign: 'center',
  },
  selectedYearOptionText: {
    color: Theme.colors.white,
    fontWeight: Theme.typography.fontWeights.semiBold,
  },
  cardActions: {
    marginTop: 0,
    borderTopWidth: 0,
    paddingTop: 0,
    alignItems: 'flex-start',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.primaryLight,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.sm + 6,
    borderRadius: Theme.borderRadius.sm,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  addButtonText: {
    marginLeft: Theme.spacing.sm,
    fontSize: Theme.typography.fontSizes.md - 1,
    color: Theme.colors.primary,
    fontWeight: Theme.typography.fontWeights.semiBold,
  },
  cardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.primaryLight,
    padding: Theme.spacing.sm,
    borderRadius: Theme.borderRadius.sm,
  },
  cardButtonText: {
    marginLeft: Theme.spacing.sm,
    fontSize: Theme.typography.fontSizes.sm,
    color: Theme.colors.primary,
    fontWeight: Theme.typography.fontWeights.medium,
  },
  welcomeSection: {
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.sm + 4,
    backgroundColor: Theme.colors.background,
  },
  welcomeText: {
    fontSize: Theme.typography.fontSizes.xxxl,
    fontWeight: Theme.typography.fontWeights.bold,
    color: Theme.colors.dark,
    flex: 1,
    flexWrap: 'wrap',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.sm,
  },
  quickTips: {
    marginHorizontal: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.primaryLight,
    borderRadius: Theme.borderRadius.sm + 2,
    padding: Theme.spacing.sm + 6,
  },
  quickTipsTitle: {
    fontSize: Theme.typography.fontSizes.md - 1,
    color: Theme.colors.primary,
    fontWeight: Theme.typography.fontWeights.bold,
    marginBottom: Theme.spacing.xs,
  },
  quickTip: {
    color: Theme.colors.medium,
    fontSize: Theme.typography.fontSizes.sm,
    marginBottom: 2,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  settingsButton: {
    padding: Theme.spacing.sm,
    borderRadius: Theme.borderRadius.round,
    backgroundColor: Theme.colors.lighter,
  },
});