import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
  },
  container: {
    padding: 20,
    backgroundColor: '#f9f9f9',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#6366f1',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#e0e7ff',
    minHeight: 170,
    justifyContent: 'space-between',
  },
  cardLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 2,
    flexShrink: 1,
    flexWrap: 'wrap',
    lineHeight: 14,
    maxWidth: '100%',
  },
  cardDescription: {
    fontSize: 13,
    color: '#6b7280',
    lineHeight: 17,
    flexShrink: 1,
    flexWrap: 'wrap',
    marginBottom: 8,
    maxWidth: '100%',
  },
  cardAmount: {
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 10,
    flexShrink: 1,
    flexWrap: 'wrap',
    marginBottom: 10,
    maxWidth: '100%',
  },
  cardTitleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  negative: {
    color: '#ff4d4f',
  },
  navSection: {
    marginTop: 20,
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  navLabel: {
    fontSize: 16,
    marginLeft: 12,
    color: '#007bff',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  yearSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  yearSelectorLabel: {
    color: '#6b7280',
    fontSize: 15,
    marginRight: 8,
  },
  yearSelectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  yearSelectorText: {
    color: '#6366f1',
    fontWeight: '600',
    fontSize: 16,
    marginRight: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearPickerContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    width: '80%',
    maxWidth: 300,
  },
  yearOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  selectedYearOption: {
    backgroundColor: '#6366f1',
  },
  yearOptionText: {
    fontSize: 16,
    color: '#1f2937',
    textAlign: 'center',
  },
  selectedYearOptionText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  cardActions: {
    marginTop: 0,
    borderTopWidth: 0,
    paddingTop: 0,
    alignItems: 'flex-start',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  addButtonText: {
    marginLeft: 8,
    fontSize: 15,
    color: '#6366f1',
    fontWeight: '600',
  },
  cardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8ff',
    padding: 8,
    borderRadius: 8,
  },
  cardButtonText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#6366f1',
    fontWeight: '500',
  },
  welcomeSection: {
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 12,
    backgroundColor: '#f9fafb',
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1f2937',
    flex: 1,
    flexWrap: 'wrap',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  quickTips: {
    marginHorizontal: 20,
    marginBottom: 16,
    backgroundColor: '#eef2ff',
    borderRadius: 10,
    padding: 14,
  },
  quickTipsTitle: {
    fontSize: 15,
    color: '#6366f1',
    fontWeight: '700',
    marginBottom: 4,
  },
  quickTip: {
    color: '#6b7280',
    fontSize: 14,
    marginBottom: 2,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  settingsButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
  },
});