import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    paddingTop: Theme.spacing.lg,
  },
  title: {
    fontSize: Theme.typography.fontSizes.xxl,
    fontWeight: Theme.typography.fontWeights.semiBold,
    marginBottom: Theme.spacing.md,
    color: Theme.colors.dark,
  },
  card: {
    backgroundColor: Theme.colors.white,
    borderRadius: Theme.borderRadius.lg,
    padding: Theme.spacing.md,
    ...Theme.shadows.sm,
  },
  inputGroup: {
    marginBottom: Theme.spacing.md,
  },
  label: {
    fontSize: Theme.typography.fontSizes.sm,
    fontWeight: Theme.typography.fontWeights.medium,
    color: Theme.colors.medium,
    marginBottom: Theme.spacing.sm,
  },
  input: {
    backgroundColor: Theme.colors.lighter,
    borderRadius: Theme.borderRadius.sm,
    padding: Theme.spacing.sm + 4,
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.dark,
    borderWidth: 1,
    borderColor: Theme.colors.light,
  },
  textarea: {
    backgroundColor: Theme.colors.lighter,
    borderRadius: Theme.borderRadius.sm,
    padding: Theme.spacing.sm + 4,
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.dark,
    borderWidth: 1,
    borderColor: Theme.colors.light,
    textAlignVertical: 'top',
  },
  saveButton: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.borderRadius.md,
    paddingVertical: Theme.spacing.md,
    alignItems: 'center',
    marginTop: Theme.spacing.md,
  },
  saveButtonText: {
    fontSize: Theme.typography.fontSizes.md,
    fontWeight: Theme.typography.fontWeights.semiBold,
    color: Theme.colors.white,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: Theme.spacing.sm + 4,
    backgroundColor: Theme.colors.lighter,
    borderRadius: Theme.borderRadius.sm,
    alignItems: 'center',
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: Theme.colors.light,
  },
  toggleButtonActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  toggleButtonText: {
    fontSize: Theme.typography.fontSizes.md,
    fontWeight: Theme.typography.fontWeights.medium,
    color: Theme.colors.medium,
  },
  toggleButtonTextActive: {
    color: Theme.colors.white,
    fontWeight: Theme.typography.fontWeights.semiBold,
  },
  contactPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.lighter,
    borderRadius: Theme.borderRadius.sm,
    padding: Theme.spacing.sm + 4,
    borderWidth: 1,
    borderColor: Theme.colors.light,
    marginBottom: Theme.spacing.md,
  },
  contactPickerText: {
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.medium,
  },
  datePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.lighter,
    borderRadius: Theme.borderRadius.sm,
    padding: Theme.spacing.sm + 4,
    borderWidth: 1,
    borderColor: Theme.colors.light,
  },
  datePickerText: {
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.dark,
  },
  loanItemContainer: {
    backgroundColor: Theme.colors.white,
    borderRadius: Theme.borderRadius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    ...Theme.shadows.sm,
  },
  loanItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  loanPersonName: {
    fontSize: Theme.typography.fontSizes.lg,
    fontWeight: Theme.typography.fontWeights.semiBold,
    color: Theme.colors.dark,
  },
  loanAmount: {
    fontSize: Theme.typography.fontSizes.lg,
    fontWeight: Theme.typography.fontWeights.bold,
    color: Theme.colors.primary,
  },
  loanItemDetails: {
    marginTop: Theme.spacing.xs,
  },
  loanItemDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.xs,
  },
  loanItemDetailText: {
    fontSize: Theme.typography.fontSizes.sm,
    color: Theme.colors.medium,
    marginLeft: Theme.spacing.xs,
  },
  loanItemActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: Theme.spacing.sm,
  },
  loanItemButton: {
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.borderRadius.sm,
    marginLeft: Theme.spacing.sm,
  },
  loanItemButtonText: {
    fontSize: Theme.typography.fontSizes.sm,
    fontWeight: Theme.typography.fontWeights.medium,
  },
  fab: {
    position: 'absolute',
    right: Theme.spacing.lg,
    bottom: 80,
    backgroundColor: Theme.colors.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadows.lg,
  },
});