import { StyleSheet } from 'react-native';
import Theme from '../constants/Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    paddingTop: 50,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.light,
  },
  backButton: {
    padding: Theme.spacing.sm,
    marginRight: Theme.spacing.sm,
  },
  headerTitle: {
    fontSize: Theme.typography.fontSizes.xl,
    fontWeight: Theme.typography.fontWeights.semiBold,
    color: Theme.colors.dark,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.light,
    marginTop: Theme.spacing.lg,
  },
  logoutText: {
    marginLeft: Theme.spacing.sm + 4,
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.error,
    fontWeight: Theme.typography.fontWeights.medium,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.white,
    padding: Theme.spacing.lg,
    borderRadius: Theme.borderRadius.lg,
    margin: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
    ...Theme.shadows.sm,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Theme.colors.light,
  },
  profileInfo: {
    marginLeft: Theme.spacing.md,
  },
  profileName: {
    fontSize: Theme.typography.fontSizes.lg,
    fontWeight: Theme.typography.fontWeights.semiBold,
    color: Theme.colors.dark,
  },
  profileEmail: {
    fontSize: Theme.typography.fontSizes.sm,
    color: Theme.colors.medium,
    marginTop: 2,
  },
  sectionHeader: {
    fontSize: Theme.typography.fontSizes.md,
    fontWeight: Theme.typography.fontWeights.bold,
    color: Theme.colors.primary,
    marginLeft: Theme.spacing.lg,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
    letterSpacing: 0.5,
  },
  card: {
    backgroundColor: Theme.colors.white,
    borderRadius: Theme.borderRadius.lg,
    marginHorizontal: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: 0,
    ...Theme.shadows.sm,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md + 2,
    paddingHorizontal: Theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.lighter,
    backgroundColor: 'transparent',
  },
  lastActionButton: {
    borderBottomWidth: 0,
  },
  actionText: {
    marginLeft: Theme.spacing.sm + 4,
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.dark,
    fontWeight: Theme.typography.fontWeights.medium,
  },
  quickTipsTitle: {
    fontSize: Theme.typography.fontSizes.md - 1,
    color: Theme.colors.primary,
    fontWeight: Theme.typography.fontWeights.bold,
    marginBottom: Theme.spacing.xs,
    marginLeft: Theme.spacing.xs,
  },
  quickTip: {
    color: Theme.colors.medium,
    fontSize: Theme.typography.fontSizes.sm,
    marginBottom: 2,
    marginLeft: Theme.spacing.xs,
  },
});